// Copyright (c) 2019 Siemens AG
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
// Author(s): Jonas Plum

package mbr

// var partitionTypes = map[uint8]string{
// 	0x00: "Empty",
// 	0x01: "FAT12 as primary partition in first physical 32 MB of disk or as logical drive anywhere on disk",
// 	0x02: "XENIX root",
// 	0x03: "XENIX usr",
// 	0x04: "FAT16 with less than 65536 sectors.",
// 	0x05: "Extended partition with CHS addressing. It must reside within the first physical 8 GB of disk, else use 0Fhinstead,Can occur in SpeedStor MBRs",
// 	0x06: "FAT16B with 65536 or more sectors. It must reside within the first 8 GB of disk unless used for logical drives in an 0Fh extended partition. Also used for FAT12 and FAT16 volumes in primary partitions if they are not residing in first physical 32 MB of disk.",
// 	0x07: "IFS,HPFS,NTFS,exFAT",
// 	0x08: "Logical sectored FAT12 or FAT16\",Partition spanning multiple drives",
// 	0x09: "AIX data/boot,\"QNX \"\"qnz\"\"\",Coherent file system,OS-9 RBF",
// 	0x0A: "OS/2 Boot Manager,Coherent swap partition",
// 	0x0B: "FAT32 with CHSaddressing",
// 	0x0C: "FAT32 with LBA",
// 	0x0E: "FAT16B with LBA",
// 	0x0F: "Extended partition with LBA",
// 	0x11: "Logical sectored FAT12 or FAT16",
// 	0x12: "Configuration partition",
// 	0x14: "Logical sectored FAT12 or FAT16",
// 	0x15: "Hidden extended partition with CHSaddressing",
// 	0x16: "Hidden FAT16B",
// 	0x17: "Hidden IFS",
// 	0x18: "AST Zero Volt Suspend or SmartSleep partition",
// 	0x19: "Willowtech Photon coS",
// 	0x1B: "Hidden FAT32",
// 	0x1C: "Hidden FAT32 with LBA",
// 	0x1E: "Hidden FAT16 with LBA",
// 	0x1F: "Hidden extended partition with LBAaddressing",
// 	0x20: "Windows Mobile update XIP,Willowsoft Overture File System",
// 	0x21: "FSo2",
// 	0x22: "Oxygen Extended Partition Table",
// 	0x23: "Windows Mobile boot XIP",
// 	0x24: "Logical sectored FAT12 or FAT16 ",
// 	0x25: "Windows Mobile IMGFS",
// 	0x27: "Windows Recovery Environment ",
// 	0x2A: "AtheOS file system",
// 	0x2B: "SyllableSecure",
// 	0x31: "Reserved",
// 	0x33: "Reserved",
// 	0x34: "Reserved",
// 	0x35: "JFS",
// 	0x36: "Reserved",
// 	0x38: "THEOS version 3.2, 2 GB partition",
// 	0x39: "Plan 9 edition 3 partition,THEOS version 4 spanned partition",
// 	0x3A: "THEOS version 4, 4 GB partition",
// 	0x3B: "THEOS version 4 extended partition",
// 	0x3C: "PqRP ",
// 	0x3D: "Hidden NetWare",
// 	0x40: "PICK R83,Venix 80286",
// 	0x41: "Personal RISC Boot,Old Linux/Minix  Boot",
// 	0x42: "Secure File system,Dynamic extended partition marker",
// 	0x43: "Old Linux native",
// 	0x44: "Norton GoBack, WildFile GoBack, Adaptec GoBack, Roxio GoBack",
// 	0x45: "Priam",
// 	0x46: "EUMEL/ELAN",
// 	0x47: "EUMEL/ELAN",
// 	0x48: "EUMEL/ELAN, ERGOS L3",
// 	0x4A: "Aquila,ALFS/THIN advanced lightweight file system for DOS",
// 	0x4C: "Aos",
// 	0x4D: "Primary QNX POSIX volume on disk",
// 	0x4E: "Secondary QNX POSIX volume on disk",
// 	0x4F: "Tertiary QNX POSIX volume on disk",
// 	0x50: "Alternative native file system,Lynx RTOS",
// 	0x51: "Read-write partition",
// 	0x52: "CP/M-80",
// 	0x53: "Auxiliary 3",
// 	0x54: "Dynamic Drive Overlay",
// 	0x55: "EZ-Drive, Maxtor, MaxBlast, or DriveGuide INT 13h redirector volume",
// 	0x56: "Logical sectored FAT12 or FAT16,Disk Manager partition converted to EZ-BIOS,VFeature partitionned volume",
// 	0x57: "VNDI partition",
// 	0x5C: "Priam EDisk Partitioned Volume",
// 	0x64: "NetWare File System 286/2,PC-ARMOUR",
// 	0x65: "NetWare File System 386",
// 	0x66: "NetWare File System 386,Storage Management Services",
// 	0x67: "Wolf Mountain",
// 	0x69: "Novell Storage Services ",
// 	0x70: "DiskSecure multiboot",
// 	0x71: "Reserved",
// 	0x72: "APTI alternative FAT12,V7/x86",
// 	0x73: "Reserved",
// 	0x74: "Reserved,Scramdisk",
// 	0x76: "Reserved",
// 	0x77: "VNDI, M2FS, M2CS",
// 	0x78: "XOSL bootloader file system",
// 	0x79: "APTI alternative FAT16",
// 	0x7A: "APTI alternative FAT16",
// 	0x7B: "APTI alternative FAT16B",
// 	0x7C: "APTI alternative FAT32",
// 	0x7D: "APTI alternative FAT32",
// 	0x7E: "Level 2 cache",
// 	0x7F: "Reserved for individual or local use and temporary or experimental projects",
// 	0x80: "MINIX file system ",
// 	0x81: "MINIX file system,Mitac Advanced Disk Manager",
// 	0x82: "Linux swap space",
// 	0x83: "Any native Linux file system ",
// 	0x84: "APM hibernation",
// 	0x85: "Linux extended",
// 	0x86: "Fault-tolerant FAT16B mirrored volume set",
// 	0x87: "Fault-tolerant HPFS/NTFS mirrored volume set",
// 	0x88: "Linux plaintext partition table",
// 	0x8A: "Linux kernel image",
// 	0x8B: "Legacy fault-tolerant FAT32 mirrored volume set",
// 	0x8C: "Legacy fault-tolerant FAT32 mirrored volume set",
// 	0x8D: "Hidden FAT12",
// 	0x8E: "Linux LVM since 1999",
// 	0x90: "Hidden FAT16",
// 	0x91: "Hidden extended partition with CHSaddressing",
// 	0x92: "Hidden FAT16B",
// 	0x93: "Amoeba native file system,Hidden Linux file system",
// 	0x94: "Amoeba bad block table",
// 	0x95: "EXOPC native",
// 	0x96: "ISO-9660 file system",
// 	0x97: "Hidden FAT32",
// 	0x98: "Hidden FAT32",
// 	0x9A: "Hidden FAT16",
// 	0x9B: "Hidden extended partition with LBA",
// 	0x9E: "ForthOS",
// 	0xA0: "Diagnostic partition for HP laptops",
// 	0xA1: "Hibernate partition",
// 	0xA2: "Hard Processor System ARM preloader",
// 	0xA5: "BSD slice ",
// 	0xA6: "OpenBSD slice",
// 	0xA8: "Apple Darwin, Mac OS X UFS",
// 	0xA9: "NetBSD slice",
// 	0xAA: "Olivetti MS-DOS FAT12",
// 	0xAB: "Apple Darwin, Mac OS X boot,GO!",
// 	0xAD: "ADFS / FileCore format",
// 	0xAE: "ShagOS file system",
// 	0xAF: "HFS and HFS+",
// 	0xB0: "Boot-Star dummy partition",
// 	0xB1: "QNX Neutrino power-safe file system",
// 	0xB2: "QNX Neutrino power-safe file system",
// 	0xB3: "QNX Neutrino power-safe file system",
// 	0xB6: "Corrupted fault-tolerant FAT16B mirrored master volume",
// 	0xB7: "BSDI native file system / swap",
// 	0xB8: "BSDI swap / native file system",
// 	0xBB: "PTS BootWizard 4 / OS Selector 5 for hidden partitions other than 01h, 04h, 06h, 07h, 0Bh, 0Ch, 0Eh and unformatted partitions,OEM Secure Zone",
// 	0xBC: "Corrupted fault-tolerant FAT32 mirrored master volume,Acronis Secure Zone,Backup Capsule",
// 	0xBE: "Solaris 8 boot",
// 	0xBF: "Solaris x86",
// 	0xC0: "Secured FAT partition",
// 	0xC1: "Secured FAT12",
// 	0xC2: "Hidden Linux native file system",
// 	0xC3: "Hidden Linux swap",
// 	0xC4: "Secured FAT16",
// 	0xC5: "Secured extended partition with CHSaddressing",
// 	0xC6: "Secured FAT16B",
// 	0xC7: "Syrinx boot,Corrupted fault-tolerant HPFS/NTFS mirrored slave volume",
// 	0xC8: "Reserved for DR-DOS since 1997",
// 	0xC9: "Reserved for DR-DOS since 1997",
// 	0xCA: "Reserved for DR-DOS since 1997",
// 	0xCB: "Secured FAT32",
// 	0xCC: "Secured FAT32",
// 	0xCD: "Memory dump",
// 	0xCE: "Secured FAT16B",
// 	0xCF: "Secured extended partition with LBA",
// 	0xD0: "Secured FAT partition",
// 	0xD1: "Secured FAT12",
// 	0xD4: "Secured FAT16",
// 	0xD5: "Secured extended partition with CHSaddressing",
// 	0xD6: "Secured FAT16B",
// 	0xD8: "CP/M-86 ",
// 	0xDA: "Non-file system data,Shielded disk",
// 	0xDB: "boot image for x86 supervisor CPU",
// 	0xDD: "Hidden memory dump",
// 	0xDE: "FAT16 utility/diagnostic partition",
// 	0xDF: "DG/UX virtual disk manager",
// 	0xE0: "ST AVFS",
// 	0xE1: "Extended FAT12",
// 	0xE2: "DOS read-only",
// 	0xE3: "DOS read-only",
// 	0xE4: "Extended FAT16",
// 	0xE5: "Logical sectored FAT12 or FAT16",
// 	0xE8: "Linux Unified Key Setup",
// 	0xEB: "BFS ",
// 	0xEC: "SkyFS",
// 	0xED: "EDC loader",
// 	0xEE: "GPT protective MBR ",
// 	0xEF: "EFI system partition. Can be a FAT12, FAT16, FAT32 ",
// 	0xF0: "\"PA-RISC Linux boot loader; must reside in first physical 2 GB\"",
// 	0xF2: "Logical sectored FAT12 or FAT16secondary partition",
// 	0xF4: "\"\"\"large\"\" DOS partition\",Single volume partition for NGF or TwinFS",
// 	0xF5: "MD0-MD9 multi volume partition for NGF or TwinFS",
// 	0xF7: "EFAT,Solid State file system",
// 	0xF9: "pCache ext2/ext3 persistent cache",
// 	0xFB: "VMware VMFS file system partition",
// 	0xFC: "VMware swap / VMKCORE kernel dump partition",
// 	0xFD: "Linux RAID superblock with auto-detect,Reserved for FreeDOS since 1997",
// 	0xFE: "partition > 1024 cylinder,Old Linux LVM ",
// 	0xFF: "XENIX bad block table",
// }
